package com.qf.dao;

import com.qf.pojo.Menuinfo;

public interface MenuinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuinfo
     *
     * @mbggenerated
     */
    int insert(Menuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuinfo
     *
     * @mbggenerated
     */
    int insertSelective(Menuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuinfo
     *
     * @mbggenerated
     */
    Menuinfo selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Menuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Menuinfo record);
}