package com.qf.pojo;

public class Menuinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuinfo.mid
     *
     * @mbggenerated
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuinfo.menuname
     *
     * @mbggenerated
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuinfo.menuicon
     *
     * @mbggenerated
     */
    private String menuicon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuinfo.menu_url
     *
     * @mbggenerated
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuinfo.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuinfo.mid
     *
     * @return the value of menuinfo.mid
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuinfo.mid
     *
     * @param mid the value for menuinfo.mid
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuinfo.menuname
     *
     * @return the value of menuinfo.menuname
     *
     * @mbggenerated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuinfo.menuname
     *
     * @param menuname the value for menuinfo.menuname
     *
     * @mbggenerated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuinfo.menuicon
     *
     * @return the value of menuinfo.menuicon
     *
     * @mbggenerated
     */
    public String getMenuicon() {
        return menuicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuinfo.menuicon
     *
     * @param menuicon the value for menuinfo.menuicon
     *
     * @mbggenerated
     */
    public void setMenuicon(String menuicon) {
        this.menuicon = menuicon == null ? null : menuicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuinfo.menu_url
     *
     * @return the value of menuinfo.menu_url
     *
     * @mbggenerated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuinfo.menu_url
     *
     * @param menuUrl the value for menuinfo.menu_url
     *
     * @mbggenerated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuinfo.parentid
     *
     * @return the value of menuinfo.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuinfo.parentid
     *
     * @param parentid the value for menuinfo.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
}