package com.qf.pojo;

public class Roleinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.roleid
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.rolename
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.shortname
     *
     * @mbggenerated
     */
    private String shortname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.roleid
     *
     * @return the value of roleinfo.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.roleid
     *
     * @param roleid the value for roleinfo.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.rolename
     *
     * @return the value of roleinfo.rolename
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.rolename
     *
     * @param rolename the value for roleinfo.rolename
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.shortname
     *
     * @return the value of roleinfo.shortname
     *
     * @mbggenerated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.shortname
     *
     * @param shortname the value for roleinfo.shortname
     *
     * @mbggenerated
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }
}